### ISSUE TITLE
AMQ7077: You are not authorized to perform the requested operation.

### ISSUE THREAD

**Issue by sushilmejari** [tongyy/ibm-mq-spring-boot-jms#1]
$ docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED
       STATUS              PORTS                    NAMES
85316ab77ca4        tony0x00/trial-mq75:v1.0   "/bin/bash"         About an hour
 ago   Up About an hour    0.0.0.0:1415->1415/tcp   mq76

ATM@ATM-PC MINGW64 ~
$ docker exec mq76 strmqm ONE.QM
AMQ7077: You are not authorized to perform the requested operation.

Please help to solve this issue

**Comment by tongyy** [comment]
It seems that you have no permission to start mq.  

Run the following commands.
1.docker exec -it $containerId /bin/bash
2.id

You will get output that looks like this, and check the user is in the mqm group
my-computer tony$ docker exec -it a4bb11a2da73 /bin/bash
root@a4bb11a2da73:/# id
uid=0(root) gid=0(root) groups=0(root),1000(mqm)

**Comment by ashish2007csGit** [comment]
sh-3.2# docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED              STATUS              PORTS                    NAMES
a0f40e69d6a1        tony0x00/trial-mq75:v1.0   "/bin/bash"         About a minute ago   Up About a minute   0.0.0.0:1415->1415/tcp   mq75
sh-3.2# docker exec mq75 strmqm ONE.QM
AMQ7077: You are not authorized to perform the requested operation.
sh-3.2# docker exec mq75 strmqm ONE.QM
sh-3.2# docker exec -it a0f40e69d6a1  /bin/bash
root@a0f40e69d6a1:/# id
uid=0(root) gid=0(root) groups=0(root)

Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203) ~[com.ibm.mq.allclient-9.0.4.0.jar:9.0.4.0 - p904-L171030.1]
	... 56 common frames omitted
Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9204: Connection to host '127.0.0.1(1415)' rejected. [1=com.ibm.mq.jmqi.JmqiException[CC=2;RC=2009;AMQ9208: Error on receive from host '/127.0.0.1:1415 (localhost)'. [1=-1,2=ffffffff,3=/127.0.0.1:1415 (localhost),4=TCP]],3=127.0.0.1(1415),5=RemoteConnection.receiveTSH]
	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:2314) ~[com.ibm.mq.allclient-9.0.4.0.jar:9.0.4.0 - p904-L171030.1]
	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1285) ~[com.ibm.mq.allclient-9.0.4.0.jar:9.0.4.0 - p904-L171030.1]
	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377) ~[com.ibm.mq.allclient-9.0.4.0.jar:9.0.4.0 - p904-L171030.1]
	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562) ~[com.ibm.mq.allclient-9.0.4.0.jar:9.0.4.0 - p904-L171030.1]
	at com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:357) ~[com.ibm.mq.allclient-9.0.4.0.jar:9.0.4.0 - p904-L171030.1]
	... 55 common frames omitted
Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host '/127.0.0.1:1415 (localhost)'. [1=-1,2=ffffffff,3=/127.0.0.1:1415 (localhost),4=TCP]


Please help me

**Comment by yasahmed** [comment]
windows : `docker exec -it  $ID_CONTAINER bash`
linux: `docker exec -it  $ID_CONTAINER /bin/bash`

then 

`sudo strmqm ONE.QM`
